In [2]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [5]:
import tensorflow as tf
print("TensorFlow version : ", tf.__version__)

TensorFlow version :  2.7.0


In [6]:
# load a data set
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11501568/11490434 [==============================] - 2s 0us/step


In [7]:
# buid a machine learning model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.13561928,  0.3278255 , -0.1955899 , -0.47914487, -0.03790156,
        -0.30120185,  0.7090508 , -0.5865128 , -0.22881034, -0.14708894]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.09046063, 0.1437908 , 0.08519512, 0.06416059, 0.09974654,
        0.07665633, 0.21052086, 0.05762872, 0.08241139, 0.089429  ]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.5684233

In [13]:
model.compile(optimizer='adam', loss = loss_fn, metrics=['accuracy'])

In [14]:
# Train and evaluate your model
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 2ms/step - loss: 0.2994 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1461 - accuracy: 0.9559
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1086 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0893 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0759 - accuracy: 0.9760


In [15]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0748 - accuracy: 0.9738 - 394ms/epoch - 1ms/step


[0.07477142661809921, 0.973800003528595]

In [16]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.42327163e-08, 1.60391256e-08, 2.15967284e-05, 1.27076855e-04,
        9.34977695e-09, 1.01493242e-07, 6.38504180e-11, 9.99818623e-01,
        1.80411701e-06, 3.08788767e-05],
       [2.15976104e-09, 1.18527005e-05, 9.99971151e-01, 1.48449117e-05,
        3.01087793e-15, 1.20160848e-06, 3.69788239e-07, 9.80942584e-12,
        6.20279991e-07, 4.19093776e-14],
       [1.42461442e-06, 9.94720578e-01, 8.19473644e-04, 2.11721981e-05,
        1.30033604e-05, 1.49192201e-05, 1.28065905e-04, 2.02064984e-03,
        2.25730077e-03, 3.41179293e-06],
       [9.99759734e-01, 1.31297839e-09, 6.39874270e-05, 8.61074767e-08,
        1.50159438e-04, 4.09963923e-06, 1.24526741e-05, 3.15107604e-06,
        3.63499142e-09, 6.35167453e-06],
       [4.22392668e-06, 4.37443443e-10, 9.54844108e-06, 3.65721377e-07,
        9.86727774e-01, 3.35617779e-06, 6.21135769e-06, 9.10472409e-06,
        3.81613745e-06, 1.32356016e-02]], dtype=float32)>